name: wakeup

on: push

jobs:
    ravi:
        runs-on: ubuntu-latest
        steps:
            - name: say hello
              run: |
                 echo "say hi"
                 echo "once again"
    ranjith:
        runs-on: ubuntu-latest
        steps:
            - name: install repo
              uses: actions/checkout@v4
            - name: list out
              run: ls

    