name: lets see
on: push

jobs:
  krish:
    runs-on: ubuntu:latest
    steps:
      - name: install code
        uses: actions/checkout@v4
      - name: install npm
        uses: actions/set-upnode@v4
        with:
          node-version: 20
      - name: install dependencies
        run: npm ci
      - name: final
        run: |
           echo "Successfull......"